modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "essentialpatcher"
version = "${version}"
displayName = "Essential Patcher"
logoFile = "icon.png"
description = "Debloats and patches the Essential mod. Unlock all cosmetics client-side, disable telemetry, remove ads/sale banners, block checkout packets, and more. Fully configurable via YACL."

[[dependencies.essentialpatcher]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.222,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.essentialpatcher]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.essentialpatcher]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.0,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "essentialpatcher.mixins.json"
