modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "essentialpatcher"
version = "${version}"
displayName = "Essential Patcher"
description = "Debloats and patches the Essential mod."

[[dependencies.essentialpatcher]]
modId = "forge"
type = "required"
versionRange = "[47.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.essentialpatcher]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "essentialpatcher.mixins.json"
